name: stasis
version: 0.1.4
authors:
  - Winton Welsh
email: mail@wintoni.us
homepage: http://stasis.me
summary: Static sites made powerful
description: Stasis is a dynamic framework for static sites.
dependencies:
  - directory_watcher
  - redis
  - slop
  - tilt
  - yajl-ruby
development_dependencies:
  - rake
  - rspec